<?php $caches=array (
  'goods' => 
  array (
    1 => 
    array (
      'id' => 1,
      'url' => 'goods-1.html',
      'upd_time' => 1590627373,
    ),
    2 => 
    array (
      'id' => '2',
      'brand_id' => '1',
      'title' => '清纯樱',
      'title_color' => '',
      'simple_desc' => '野蛮拳击女友清纯樱实体娃娃',
      'model' => '',
      'place_origin' => '19',
      'inventory' => '12000',
      'inventory_unit' => '个',
      'images' => '/static/upload/images/goods/2020/01/05/1578203616414517.jpg',
      'original_price' => '0.00-1500.00',
      'min_original_price' => '0.00',
      'max_original_price' => '1500.00',
      'price' => '950.00-3250.00',
      'min_price' => '950.00',
      'max_price' => '3250.00',
      'give_integral' => '100',
      'buy_min_number' => '1',
      'buy_max_number' => '0',
      'is_deduction_inventory' => '1',
      'is_shelves' => '1',
      'is_home_recommended' => '1',
      'content_web' => '<p><img src="/static/upload/images/goods/2020/01/05/1578203341345152.jpg" title="野蛮拳击女友清纯樱" alt="野蛮拳击女友清纯樱"/></p><p><img src="/static/upload/images/goods/2020/01/05/1578203342330341.jpg" title="野蛮拳击女友清纯樱：全新S级妆容" alt="野蛮拳击女友清纯樱：全新S级妆容"/></p><p><img src="/static/upload/images/goods/2020/01/05/1578203342448437.jpg" title="野蛮拳击女友清纯樱：多功能可选，环保TPE" alt="野蛮拳击女友清纯樱：多功能可选，环保TPE"/></p><p><img src="/static/upload/images/goods/2020/01/05/1578203342161491.jpg" title="野蛮拳击女友清纯樱：可动合金骨架" alt="野蛮拳击女友清纯樱：可动合金骨架"/></p><p><img src="/static/upload/images/goods/2020/01/05/1578203343192330.jpg" title="野蛮拳击女友清纯樱：胸围、腰围和臀围的尺码表" alt="野蛮拳击女友清纯樱：胸围、腰围和臀围的尺码表"/></p><p><img src="/static/upload/images/goods/2020/01/05/1578203343864756.jpg" title="野蛮拳击女友清纯樱：再来一场大汗淋漓的肉搏战" alt="野蛮拳击女友清纯樱：再来一场大汗淋漓的肉搏战"/></p><p><img src="/static/upload/images/goods/2020/01/05/1578203344629623.jpg" title="野蛮拳击女友清纯樱：我的野蛮女友，身体的秘密" alt="野蛮拳击女友清纯樱：我的野蛮女友，身体的秘密"/></p><p><img src="/static/upload/images/goods/2020/01/05/1578203344420213.jpg" title="野蛮拳击女友清纯樱：迷人的五官，经过专业的模型师和巧手化妆的精雕细琢，赋予了她迷人的五官" alt="野蛮拳击女友清纯樱：迷人的五官，经过专业的模型师和巧手化妆的精雕细琢，赋予了她迷人的五官"/></p><p><img src="/static/upload/images/goods/2020/01/05/1578203345756184.jpg" title="野蛮拳击女友清纯樱：惹火的翘臀，紧握它，感受柔软的迷魂刺激" alt="野蛮拳击女友清纯樱：惹火的翘臀，紧握它，感受柔软的迷魂刺激"/></p><p><img src="/static/upload/images/goods/2020/01/05/1578203345417823.jpg" title="野蛮拳击女友清纯樱：云润丰满的翘臀，逼真紧致的双通道" alt="野蛮拳击女友清纯樱：云润丰满的翘臀，逼真紧致的双通道"/></p><p><img src="/static/upload/images/goods/2020/01/05/1578203346624103.jpg" title="野蛮拳击女友清纯樱：娃娃实拍图，正面站姿" alt="野蛮拳击女友清纯樱：娃娃实拍图，正面站姿"/></p><p><img src="/static/upload/images/goods/2020/01/05/1578203347230111.jpg" title="野蛮拳击女友清纯樱：娃娃实拍图，正面跪姿" alt="野蛮拳击女友清纯樱：娃娃实拍图，正面跪姿"/></p><p><img src="/static/upload/images/goods/2020/01/05/1578203347689837.jpg" title="野蛮拳击女友清纯樱：娃娃实拍图，正面上半身跪姿，肩带装" alt="野蛮拳击女友清纯樱：娃娃实拍图，正面上半身跪姿，肩带装"/></p><p><img src="/static/upload/images/goods/2020/01/05/1578203348962872.jpg" title="野蛮拳击女友清纯樱：娃娃实拍图，正面上半身跪姿，牛仔热裤装" alt="野蛮拳击女友清纯樱：娃娃实拍图，正面上半身跪姿，牛仔热裤装"/></p><p><img src="/static/upload/images/goods/2020/01/05/1578203348524766.jpg" title="野蛮拳击女友清纯樱：娃娃实拍图，正面坐姿图，肉体的碰撞" alt="野蛮拳击女友清纯樱：娃娃实拍图，正面坐姿图，肉体的碰撞"/></p><p><img src="/static/upload/images/goods/2020/01/05/1578203349128672.jpg" title="野蛮拳击女友清纯樱：娃娃实拍图，正面半跪姿图，等你大战一场" alt="野蛮拳击女友清纯樱：娃娃实拍图，正面半跪姿图，等你大战一场"/></p><p><img src="/static/upload/images/goods/2020/01/05/1578202905792886.jpg" alt="实体娃娃头型选择，拍下备注留言"/><img src="/static/upload/images/goods/2020/01/05/1578202905297530.jpg" alt="实体娃娃肤色和瞳色选择"/><img src="/static/upload/images/goods/2020/01/05/1578202905194503.jpg" alt="实体娃娃甲色选择"/><img src="/static/upload/images/goods/2020/01/05/1578202906907347.jpg" alt="实体娃娃站立功能演示"/><img src="/static/upload/images/goods/2020/01/05/1578202906432549.jpg" alt="实体娃娃使用注意事项"/><img src="/static/upload/images/goods/2020/01/05/1578202907923822.jpg" alt="实体娃娃可活动范围"/><img src="/static/upload/images/goods/2020/01/05/1578202907832760.jpg" alt="实体娃娃检测报告"/><img src="/static/upload/images/goods/2020/01/05/1578202907230318.jpg" alt="实体娃娃测试报告"/><img src="/static/upload/images/goods/2020/01/05/1578202908875410.jpg" alt="实体娃娃买家须知"/><img src="/static/upload/images/goods/2020/01/05/1578202908225119.jpg" alt="实体娃娃护理和破损修复方法"/></p>',
      'photo_count' => '5',
      'sales_count' => '26',
      'access_count' => '1348',
      'video' => '/static/upload/video/goods/2020/01/04/1578138219565877.mp4',
      'home_recommended_images' => '/static/upload/images/goods/2020/01/05/1578203616414517.jpg',
      'plugins_membershiplevelvip_price_extends' => '',
      'is_exist_many_spec' => '1',
      'spec_base' => '[{"title":"\\u8eab\\u9ad8","value":["100","110","130","135","145","158","165"]},{"title":"\\u80f8\\u578b","value":["\\u5e73\\u80f8","\\u5c0f\\u80f8","\\u4e2d\\u80f8","\\u5927\\u80f8"]},{"title":"\\u529f\\u80fd","value":["\\u65e0","\\u53ef\\u7ad9\\u7acb","\\u52a0\\u6e29","\\u667a\\u80fd\\u5bf9\\u8bdd","\\u667a\\u80fd\\u5bf9\\u8bdd+\\u89e6\\u6478\\u53d1\\u97f3","\\u53ef\\u7ad9\\u7acb+\\u52a0\\u6e29","\\u53ef\\u7ad9\\u7acb+\\u667a\\u80fd\\u5bf9\\u8bdd","\\u53ef\\u7ad9\\u7acb+\\u667a\\u80fd\\u5bf9\\u8bdd+\\u89e6\\u6478\\u53d1\\u97f3","\\u52a0\\u6e29+\\u667a\\u80fd\\u5bf9\\u8bdd","\\u52a0\\u6e29+\\u667a\\u80fd\\u5bf9\\u8bdd+\\u89e6\\u6478\\u53d1\\u97f3","\\u53ef\\u7ad9\\u7acb+\\u52a0\\u6e29+\\u667a\\u80fd\\u5bf9\\u8bdd","\\u53ef\\u7ad9\\u7acb+\\u52a0\\u6e29+\\u667a\\u80fd\\u5bf9\\u8bdd+\\u89e6\\u6478\\u53d1\\u97f3"]}]',
      'fictitious_goods_value' => '',
      'seo_title' => '清纯樱-野蛮拳击女友实体娃娃-馒头饭娃娃',
      'seo_keywords' => '',
      'seo_desc' => '野蛮拳击女友清纯樱实体娃娃',
      'is_delete_time' => '0',
      'upd_time' => '1584600179',
      'max_buy_integral' => '1000',
      'url' => 'goods-2.html',
    ),
    3 => 
    array (
      'id' => 3,
      'url' => 'goods-3.html',
      'upd_time' => 1590626999,
    ),
    4 => 
    array (
      'id' => 4,
      'url' => 'goods-4.html',
      'upd_time' => 1589632587,
    ),
    5 => 
    array (
      'table_catalog' => 'def',
      'table_schema' => 'wwshop',
      'table_name' => 's_goods',
      'table_type' => 'BASE TABLE',
      'engine' => 'InnoDB',
      'version' => '10',
      'row_format' => 'Dynamic',
      'table_rows' => '4',
      'avg_row_length' => '20480',
      'data_length' => '81920',
      'max_data_length' => '0',
      'index_length' => '65536',
      'data_free' => '0',
      'auto_increment' => '5',
      'create_time' => '2020-02-11 12:38:01',
      'update_time' => '2020-05-20 03:00:00',
      'check_time' => NULL,
      'table_collation' => 'utf8mb4_general_ci',
      'checksum' => NULL,
      'create_options' => 'row_format=DYNAMIC',
      'table_comment' => '商品',
      'id' => '5',
      'url' => 'goods-5.html',
      'upd_time' => 1589950598,
    ),
    6 => 
    array (
      'id' => 6,
      'url' => 'goods-6.html',
      'upd_time' => 1589951250,
    ),
  ),
  'article' => 
  array (
    30 => 
    array (
      'id' => '30',
      'title' => 'M站娃娃邀请您成为首席体验官',
      'article_category_id' => '25',
      'title_color' => '#FF3366',
      'jump_url' => '',
      'is_enable' => '1',
      'content' => '<p>即日起，在M站娃娃购买任意娃娃，评价晒单，符合如下要求：</p><p>1 评价不少于50字</p><p>2 照片不少于3张</p><p><br/></p><p>将评价截图给客服，注明您的 M站娃娃 帐号（邮箱/手机号），我们将一次性奖励您 50元 无门槛现金优惠券 一张。</p><p><br/></p>',
      'images' => '',
      'images_count' => '0',
      'access_count' => '20',
      'is_home_recommended' => '1',
      'seo_title' => '',
      'seo_keywords' => '',
      'seo_desc' => '',
      'upd_time' => '1584174836',
      'url' => 'article-30.html',
    ),
    27 => 
    array (
      'id' => '27',
      'title' => '招聘英才',
      'article_category_id' => '24',
      'title_color' => '',
      'jump_url' => '',
      'is_enable' => '1',
      'content' => '<h2>PHP工程师</h2><p>岗位描述：</p><p>1.负责项目后端系统的研发和维护工作。</p><p>2.负责跟进平台的运营监控和数据分析工作。</p><p>3.按时保质保量完成项目开发,研究新兴技术，持续优化系统架构，完善基础服务。<br/></p><p>4.思维敏捷,责任心强,能承受工作压力。</p><p><br/></p><p>任职资格：</p><p>1、本科及以上学历，计算机相关专业，3年以上相关开发工作经验。</p><p>2、精通基于LNMP的Web开发技术, 熟悉yii, yaf, ThinkPHP, zend等框架的是用及实现原理。</p><p>3、熟悉mysql、redis等应用开发，精通SQL调优和数据结构设计。</p><p>4、熟悉使用Javascript、Ajax，Html，Div+CSS，Vue等技术。</p><p>5、有大型项目开发经验，系统调优经验者优先。</p><p>6、对LNMP/LAMP架构的部署、搭建、优化、排错等方面有经验者优先。</p><p>7、事业心强，勤奋好学，有团队精神。</p><p><br/></p><h2>前端工程师</h2><p>岗位描述：</p><p>1.配合项目经理和设计师快速实现一流的前端界面，优化代码并保持良好的兼容性，改善用户体验。</p><p>2.根据业务和项目需求，进行技术创新，分析并给出最优的前台技术实现方案。</p><p>3.对前端开发的新技术有敏锐嗅觉，推进前端技术演进。</p><p>4.进行新技术调研，持续对产品前端进行维护和升级。</p><p><br/></p><p>任职资格：</p><p>1、了解Web 标准，熟悉 HTML、CSS、JavaScript 各种前端技术。</p><p>2、熟悉 HTTP 协议。</p><p>3、认真负责，积极主动，有良好的团队合作意识。</p><p>4、了解 Angularjs，前端工程化或者 Node.js 等技术有研究。</p><p>5、有Vue开发经验者优先。</p><p>6、事业心强，勤奋好学，有团队精神。</p><p><br/></p>',
      'images' => '',
      'images_count' => '0',
      'access_count' => '79',
      'is_home_recommended' => '1',
      'seo_title' => '',
      'seo_keywords' => '',
      'seo_desc' => '',
      'upd_time' => '1584025930',
      'url' => 'article-27.html',
    ),
    29 => 
    array (
      'id' => '29',
      'title' => '关于M站娃娃',
      'article_category_id' => '24',
      'title_color' => '',
      'jump_url' => '',
      'is_enable' => '1',
      'content' => '<p>M站娃娃，是一家实体娃娃商城，主打高端低价可定制的实体娃娃产品。</p>',
      'images' => '',
      'images_count' => '0',
      'access_count' => '78',
      'is_home_recommended' => '1',
      'seo_title' => '',
      'seo_keywords' => '',
      'seo_desc' => '',
      'upd_time' => '1584025869',
      'url' => 'article-29.html',
    ),
    26 => 
    array (
      'id' => '26',
      'title' => '合作及洽谈',
      'article_category_id' => '24',
      'title_color' => '',
      'jump_url' => '',
      'is_enable' => '1',
      'content' => '<p>M站娃娃致力于提供高端低价的一手娃娃，娃娃用户体检极佳，综合评价较好，并且我们可以保障良好的售后服务。</p><p>诚邀各类合作，请与我们联系：</p><p>电话：13036888204</p><p>微信号：madfan</p><p><br/></p>',
      'images' => '',
      'images_count' => '0',
      'access_count' => '68',
      'is_home_recommended' => '1',
      'seo_title' => '',
      'seo_keywords' => '',
      'seo_desc' => '',
      'upd_time' => '1584025431',
      'url' => 'article-26.html',
    ),
    23 => 
    array (
      'id' => '23',
      'title' => '会员修改个人资料',
      'article_category_id' => '7',
      'title_color' => '',
      'jump_url' => '',
      'is_enable' => '1',
      'content' => '<p>M站娃娃会员需要修改个人资料，可以进入个人中心，移动端请点击我。<br/></p><p>点击 资料管理，进入 个人资料 页面。</p><p>可以修改 头像，昵称，性别，生日，手机号和电子邮箱。</p>',
      'images' => '',
      'images_count' => '0',
      'access_count' => '80',
      'is_home_recommended' => '1',
      'seo_title' => '',
      'seo_keywords' => '',
      'seo_desc' => '',
      'upd_time' => '1584025422',
      'url' => 'article-23.html',
    ),
    22 => 
    array (
      'id' => '22',
      'title' => '会员修改密码',
      'article_category_id' => '7',
      'title_color' => '',
      'jump_url' => '',
      'is_enable' => '1',
      'content' => '<p>【修改密码】</p><p>请您先登录M站娃娃，进入个人中心，资料管理，安全设置，登录密码，修改。</p><p>输入旧密码，要设置的新密码，重复输入一次新密码，即可修改密码。</p><p>【忘记密码】</p><p>进入M站娃娃的登录页，点 忘记密码，输入您绑定的 手机号 或 邮箱，点 获取验证码，然后打开手机或登录邮箱，收取验证码。</p><p>输入您收到的验证码，即可重新设置密码。</p>',
      'images' => '',
      'images_count' => '0',
      'access_count' => '92',
      'is_home_recommended' => '1',
      'seo_title' => '',
      'seo_keywords' => '',
      'seo_desc' => '',
      'upd_time' => '1584025278',
      'url' => 'article-22.html',
    ),
    28 => 
    array (
      'id' => '28',
      'title' => '联系我们',
      'article_category_id' => '24',
      'title_color' => '',
      'jump_url' => '',
      'is_enable' => '1',
      'content' => '<p>联系我们：admin@dm126.com<br/></p><p>电话：130 3688 8204</p>',
      'images' => '',
      'images_count' => '0',
      'access_count' => '187',
      'is_home_recommended' => '1',
      'seo_title' => '联系我们',
      'seo_keywords' => '联系我们',
      'seo_desc' => '',
      'upd_time' => '1584004430',
      'url' => 'article-28.html',
    ),
    13 => 
    array (
      'id' => '13',
      'title' => 'TPE材质的实体娃娃破损修复方法',
      'article_category_id' => '7',
      'title_color' => '',
      'jump_url' => '',
      'is_enable' => '1',
      'content' => '<p>1 假如娃娃表面小面积损伤，可以使用配送的胶水进行粘合。第一线将破损面清洗干净，将伤口处的胶料恢复到原位，在均匀涂上一层胶水，半小时后左右干固即可。不会修补或者有其他疑问，请勿申请退款，拍好视频联系我们，我们会根据你娃娃的具体情况提供针对性方案处理。</p><p><br/></p><p>2 娃娃表皮出现不同程度的开裂、破损，请立即停止使用，尽快进行有效修补。修补方法请见第1条。如果有面积较大、破损严重的情况请勿直接修补，拍好视频联系我们，我们会根据您娃娃的具体情况提供针对性方案处理，或退回本店进行修复。</p>',
      'images' => '',
      'images_count' => '0',
      'access_count' => '88',
      'is_home_recommended' => '1',
      'seo_title' => 'TPE材质的实体娃娃破损修复方法-馒头饭娃娃',
      'seo_keywords' => '',
      'seo_desc' => '',
      'upd_time' => '1583679950',
      'url' => 'article-13.html',
    ),
    7 => 
    array (
      'id' => '7',
      'title' => 'TPE材质的实体娃娃日常护理方法',
      'article_category_id' => '7',
      'title_color' => '',
      'jump_url' => '',
      'is_enable' => '1',
      'content' => '<p>1、娃娃身体内部装有各个关节，可在一定范围内摆出各种姿势。但因产品出厂时为自然直身姿势，所以不能长时间让娃娃摆放或保持高难度弯曲的姿势，以免变形损坏。</p><p><br/></p><p>2、如娃娃表面有灰尘和污物，使用一般洗涤剂便可清洗，如洗衣粉和沐浴露。切勿大面积大力抓娃娃表面。清洗干净后自然风干水粉，在娃娃身上均匀涂上赠送的名器保护粉，让娃娃表面光滑如初，手感细腻。</p><p><br/></p><p>3、娃娃平均10-20天洗澡一次，洗澡后涂抹保护粉，防止出油裂开。长时间压迫一侧可产生压痕，将压面朝上，几天后可自行恢复。</p><p><br/></p><p>4、如果娃娃不小心染色，可以使用我们配送的祛色膏。将祛色膏均匀的涂在染色位置，擦好之后将娃娃置于干燥阴凉处，过24小时染色位置可自行消除。</p><p><br/></p><p>5、娃娃不可长期受日光照射，建议放在干燥阴凉处，并且保持放置环境干净卫生，同时建议放在5-35度范围之间，注意避免温度或高或低，如遇寒冷温度过低情况，可使用电热毯包裹对娃娃加温，因为TPE具有一定的耐热性，但请注意温度和时间。请勿放置重物在娃娃身上，日常请将娃娃平躺，请勿将娃娃放置在儿童可触及的地方。</p>',
      'images' => '',
      'images_count' => '0',
      'access_count' => '80',
      'is_home_recommended' => '1',
      'seo_title' => 'TPE材质的实体娃娃日常护理方法-馒头饭娃娃',
      'seo_keywords' => '',
      'seo_desc' => '',
      'upd_time' => '1583679673',
      'url' => 'article-7.html',
    ),
    12 => 
    array (
      'id' => '12',
      'title' => '分期付款',
      'article_category_id' => '16',
      'title_color' => '',
      'jump_url' => '',
      'is_enable' => '1',
      'content' => '<p>如果您想要通过分期付款的方式，购买M站娃娃上的商品。</p><p>强烈建议您通过 手机浏览器或者电脑浏览器，输入网址：mall.mantoufan.com，访问M站娃娃商城。</p><p>然后购买您想要的商品，在付款时，使用 支付宝 等支持 分期付款的方式。<br/></p><p>这里以支付宝的花呗分期为例：</p><p>如果您的账户可以支持 花呗分期，则在您可以在 支付宝扫码后，选择花呗分期方式付款。</p><p>分期付款通常需要您承担一定数额的手续费，该费用由 分期付款的提供商 收取，M站娃娃并不会因此多收您的钱。</p>',
      'images' => '',
      'images_count' => '0',
      'access_count' => '51',
      'is_home_recommended' => '1',
      'seo_title' => '',
      'seo_keywords' => '',
      'seo_desc' => '',
      'upd_time' => '1583422519',
      'url' => 'article-12.html',
    ),
    16 => 
    array (
      'id' => '16',
      'title' => '在线支付',
      'article_category_id' => '16',
      'title_color' => '',
      'jump_url' => '',
      'is_enable' => '1',
      'content' => '<p>M站娃娃目前支持三种在线支付方式，分别是：</p><p>1 微信支付</p><p>2 支付宝支付</p><p>3 QQ钱包支持</p><p><br/></p><p>在某些特定环境下，比如微信中，只有微信支付是可用的。</p><p>如果您想要完整选择三种支付方式，建议您使用 手机浏览器或电脑浏览器，访问网址：mall.mantoufan.com</p><p>选择您需要的支付方式付款。</p>',
      'images' => '',
      'images_count' => '0',
      'access_count' => '66',
      'is_home_recommended' => '1',
      'seo_title' => '',
      'seo_keywords' => '',
      'seo_desc' => '',
      'upd_time' => '1583422467',
      'url' => 'article-16.html',
    ),
    3 => 
    array (
      'id' => '3',
      'title' => '积分细则',
      'article_category_id' => '7',
      'title_color' => '#FF0000',
      'jump_url' => '',
      'is_enable' => '1',
      'content' => '<p>M站娃娃注册会员，可以通过购买商品、评论等方式（具体获取方式，请以实际执行规则为准）获得积分。</p><p>积分通常可以用来兑换礼品，抵扣现金（具体使用方式，请以实际执行规则为准）</p><p>M站娃娃保留随时变更 积分获取途径及使用方式 的权利，以上规则并不构成对积分的承诺。</p>',
      'images' => '',
      'images_count' => '0',
      'access_count' => '65',
      'is_home_recommended' => '1',
      'seo_title' => '',
      'seo_keywords' => '',
      'seo_desc' => '',
      'upd_time' => '1583074898',
      'url' => 'article-3.html',
    ),
    1 => 
    array (
      'id' => '1',
      'title' => '如何注册成为会员',
      'article_category_id' => '7',
      'title_color' => '',
      'jump_url' => '',
      'is_enable' => '1',
      'content' => '<p>M站娃娃开放多种注册方式：</p><p>您可以通过：</p><p>1 邮箱</p><p>2 手机号</p><p>3 第三方帐号</p><p>注册成为M站娃娃会员，享受会员服务。</p><p>如果您只想临时下单，可以点击 免注册购买 按钮，获得临时的会员账号，该账号与您的浏览器绑定，如果您清空了历史记录，或者更换了电脑，则帐号失效。</p><p>我们强烈建议您，使用上面的三种方式，注册为会员，再购买。</p>',
      'images' => '',
      'images_count' => '0',
      'access_count' => '244',
      'is_home_recommended' => '1',
      'seo_title' => '',
      'seo_keywords' => '',
      'seo_desc' => '',
      'upd_time' => '1583074772',
      'url' => 'article-1.html',
    ),
    4 => 
    array (
      'id' => '4',
      'title' => '积分兑换说明',
      'article_category_id' => '17',
      'title_color' => '',
      'jump_url' => '',
      'is_enable' => '1',
      'content' => '<p>积分兑换说明</p><p>积分兑换说明</p><p>积分兑换说明</p><p>积分兑换说明</p><p>积分兑换说明</p><p>积分兑换说明</p>',
      'images' => '[]',
      'images_count' => '0',
      'access_count' => '52',
      'is_home_recommended' => '1',
      'seo_title' => '',
      'seo_keywords' => '',
      'seo_desc' => '',
      'upd_time' => '1534228520',
      'url' => 'article-4.html',
    ),
  ),
);?>